CREATE DATABASE IF NOT EXISTS trilho;

USE trilho;

CREATE TABLE posts (
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
	author VARCHAR(255) NOT NULL,
    image_resource VARCHAR(255) NOT NULL,
	content LONGTEXT NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);